[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[global_norm]
state_len = 5

[scaling]
strategy = "pa"

[run_info]
sample_rate = 5000

[standardisation]
standardise = 1
mean = 93.38
stdev = 23.42

[qscore]
scale = 1.05
bias = 0.2

[encoder]
type = "serial"
[[encoder.sublayers]]
type = "convolution"
insize = 1
size = 16
bias = true
winlen = 5
stride = 1
padding = 2
activation = "swish"
norm = "batchnorm"

[[encoder.sublayers]]
type = "convolution"
insize = 16
size = 16
bias = true
winlen = 5
stride = 1
padding = 2
activation = "swish"
norm = "batchnorm"

[[encoder.sublayers]]
type = "convolution"
insize = 16
size = 1024
bias = true
winlen = 19
stride = 6
padding = 9
activation = "tanh"
norm = "batchnorm"

[[encoder.sublayers]]
type = "permute"
dims = [ 2, 0, 1,]

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 1

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 0

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 1

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 0

[[encoder.sublayers]]
type = "lstm"
size = 1024
insize = 1024
bias = true
reverse = 1

[[encoder.sublayers]]
type = "linearcrfencoder"
insize = 1024
n_base = 4
state_len = 5
bias = false
blank_score = 2.0

[[encoder.sublayers]]
type = "clamp"
min = -5.0
max = 5.0

[basecaller]
batchsize = 96
chunksize = 10000
overlap = 500
